<a href="https://colab.research.google.com/github/Mayra-99/atelier_numpy/blob/main/atelier_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contexte Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique. Les données doivent être préparées et analysées avant d'être transmises à un futur système de Machine Learning permettant de détecter des situations anormales

Partie 1 : Listes Python vs tableaux NumPy On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8  
1) Créer une liste Python stockant ces températures;
 2) Créer un tableau NumPy équivalent stockant ces températures ;
 3) Effectuer une multiplication par 2 sur ces deux collections;
  4) Quelle différence observe-t-on ?

In [13]:
!pip install numpy

In [14]:
import numpy as np


In [15]:
# creer une liste python stokant les temperature
listes_simple=[24.5, 25.1, 26.3, 27.0 ,25.8]
print (listes_simple)

[24.5, 25.1, 26.3, 27.0, 25.8]


In [16]:
#Créer un tableau NumPy équivalent stockant ces températures
listes_np=np.array([24.5, 25.1, 26.3, 27.0 ,25.8])
print (listes_np)

[24.5 25.1 26.3 27.  25.8]


In [17]:
## Effectuer une multiplication par 2 sur ces deux collections;
manup=listes_np*2
print (manup)

[49.  50.2 52.6 54.  51.6]


In [19]:
# Effectuer une multiplication par 2 sur ces deux collections;
manup1=listes_simple*2
print (manup1)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]


Quelle différence observe-t-on ?

liste_simple * 2 → duplique la liste
 (tu obtiens 10 éléments : la liste répétée deux fois).
liste_np * 2 → multiplie chaque température par 2
(tu obtiens toujours 5 éléments, mais chacun doublé).

C'est exactement la démonstration qu'un tableau NumPy fait du vrai calcul, une liste Python non.



Partie 2 – Création des données
 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.
 2) Créer un tableau contenant 10 valeurs égales à 1.
 3) Créer un tableau de 10 valeurs initialisées à 25.
  4) Créer une matrice identité de taille 5 × 5.
  5) Créer les 24 heures (de 0 à 23) de mesure d’une journée
  6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C
  7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [20]:
#Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.
temperature_zero=np.zeros(10)
print (temperature_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
#Créer un tableau contenant 10 valeurs égales à 1.
temperature_un=np.ones(10)
print (temperature_un)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
#Créer un tableau de 10 valeurs initialisées à 25.
temperature_25=np.full(10,25)
print (temperature_25)


[25 25 25 25 25 25 25 25 25 25]


In [24]:
#Créer une matrice identité de taille 5 × 5.
matrice_identite=np.eye(5)
print (matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
#Créer les 24 heures (de 0 à 23) de mesure d’une journée
heure=np.arange(24)
print (heure)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [27]:
#Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C
temperature_20_30=np.linspace(20,30,10)
print (temperature_20_30)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


In [34]:
#Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductible
np.random.seed(7)
temperature_aleatoire=np.random.randint(15,39,100)
print (temperature_aleatoire)

[30 19 37 18 34 38 22 29 38 23 29 25 23 22 21 19 31 22 27 15 26 38 21 34
 27 20 38 36 31 15 17 24 29 21 19 29 24 38 18 18 23 34 31 16 15 31 37 27
 22 38 25 24 18 15 22 38 38 15 36 19 18 16 18 16 34 19 34 16 20 24 32 17
 34 33 33 36 38 18 26 30 31 27 26 24 24 27 18 29 29 35 36 30 18 31 19 26
 23 37 26 30]
