<a href="https://colab.research.google.com/github/Mayra-99/atelier_numpy/blob/main/atelier_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contexte Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique. Les données doivent être préparées et analysées avant d'être transmises à un futur système de Machine Learning permettant de détecter des situations anormales

#
Partie 1 : Listes Python vs tableaux NumPy On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8  
1) Créer une liste Python stockant ces températures;
 2) Créer un tableau NumPy équivalent stockant ces températures ;
 3) Effectuer une multiplication par 2 sur ces deux collections;
  4) Quelle différence observe-t-on ?

In [2]:
!pip install numpy

In [3]:
import numpy as np


In [4]:
# creer une liste python stokant les temperature
listes_simple=[24.5, 25.1, 26.3, 27.0 ,25.8]
print (listes_simple)

[24.5, 25.1, 26.3, 27.0, 25.8]


In [5]:
#Créer un tableau NumPy équivalent stockant ces températures
listes_np=np.array([24.5, 25.1, 26.3, 27.0 ,25.8])
print (listes_np)

[24.5 25.1 26.3 27.  25.8]


In [6]:
## Effectuer une multiplication par 2 sur ces deux collections;
manup=listes_np*2
print (manup)

[49.  50.2 52.6 54.  51.6]


In [7]:
# Effectuer une multiplication par 2 sur ces deux collections;
manup1=listes_simple*2
print (manup1)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]



Quelle différence observe-t-on ?**texte en gras**

liste_simple * 2 → duplique la liste
 (tu obtiens 10 éléments : la liste répétée deux fois).
liste_np * 2 → multiplie chaque température par 2
(tu obtiens toujours 5 éléments, mais chacun doublé).

C'est exactement la démonstration qu'un tableau NumPy fait du vrai calcul, une liste Python non.



#
Partie 2 – Création des données
 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.
 2) Créer un tableau contenant 10 valeurs égales à 1.
 3) Créer un tableau de 10 valeurs initialisées à 25.
  4) Créer une matrice identité de taille 5 × 5.
  5) Créer les 24 heures (de 0 à 23) de mesure d’une journée
  6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C
  7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [8]:
#Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.
temperature_zero=np.zeros(10)
print (temperature_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#Créer un tableau contenant 10 valeurs égales à 1.
temperature_un=np.ones(10)
print (temperature_un)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
#Créer un tableau de 10 valeurs initialisées à 25.
temperature_25=np.full(10,25)
print (temperature_25)


[25 25 25 25 25 25 25 25 25 25]


In [11]:
#Créer une matrice identité de taille 5 × 5.
matrice_identite=np.eye(5)
print (matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
#Créer les 24 heures (de 0 à 23) de mesure d’une journée
heure=np.arange(24)
print (heure)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [13]:
#Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C
temperature_20_30=np.linspace(20,30,10)
print (temperature_20_30)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


In [14]:
#Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductible
np.random.seed(7)
temperature_aleatoire=np.random.uniform(-15,39,100).round(2)
print (temperature_aleatoire)

[-10.88  27.12   8.67  24.07  37.81  14.08  12.06 -11.11  -0.5   11.99
  21.68  28.4    5.57 -11.44   0.56  34.12  -3.48   9.41  35.29 -13.66
  17.43  36.31  -2.56  14.62  34.09  -7.81  13.26  25.52  21.13  10.26
  -3.94  11.5    5.11  10.78   4.76  30.25  26.51   1.96  15.92  -0.09
   9.45   4.06  20.5    5.     9.79  23.84   7.3   33.95  -5.26  25.02
   7.81   8.03  19.26  13.24   7.4  -14.92 -10.02  23.31  13.31  22.59
  36.6   21.88 -12.13   1.68  17.    -2.3   37.11  36.03  30.81  10.51
  30.44  -7.92   1.67  10.    25.06  11.23  -7.61   3.55   2.52   1.22
  -6.06   7.4    9.2   26.84  28.01  13.21   9.87  27.02  32.91  21.45
  28.23  35.71 -12.8   32.29  -0.07  10.69  28.03  23.73  -7.05  20.57]


#
Partie 3 – Exploration des tableaux
 1) Créer aléatoirement un tableau représentant les 24 températures d'une journée :
 2) Déterminer les propriétés suivantes du tableau

  a) nombre de    dimensions ;

  b) nombre de valeurs ;

  c) type des données ;
  
   d) forme du tableau.

In [15]:
#Créer aléatoirement un tableau représentant les 24 températures d'une journée :
np.random.seed(12)
temperatures_jour = np.random.uniform(15, 45, 24).round(2)
print(temperatures_jour)



[19.62 37.2  22.9  31.01 15.44 42.56 42.02 16.   43.71 19.12 23.51 33.18
 43.33 40.58 15.07 30.64 31.56 29.56 38.04 19.82 37.94 15.62 19.06 18.49]


In [16]:
#a) nombre de dimensions
print(temperatures_jour.ndim)

1


In [17]:
#b) nombre de valeurs
print(temperatures_jour.size)

24


In [18]:
#c) type des données
print(temperatures_jour.dtype)

float64


In [19]:
#d) forme du tableau.
print(temperatures_jour.shape) # nombre d'elements

(24,)


#
Partie 4 – Indexation et slicing Considérant le tableau représentant les 24 températures d'une journée, afficher
:
1) la première mesure ;

 2) la dernière mesure ;

3) la température de 8h ;
 4) les températures de 8h
 à 12h ;
 5) les températures des 6 premières heures ;

 6) les températures des heures paires.

In [20]:
#la première mesure
print(temperatures_jour[0])

19.62


In [21]:
#la dernière mesure ;
print(temperatures_jour[-1])

18.49


In [22]:
#la température de 8h
print(temperatures_jour[8])

43.71


In [23]:
#les températures de 8h à 12h
print(temperatures_jour[8:13])

[43.71 19.12 23.51 33.18 43.33]


In [24]:
#les températures des 6 premières heures
print(temperatures_jour[:6])

[19.62 37.2  22.9  31.01 15.44 42.56]


In [25]:
#les températures des heures paires.
print(temperatures_jour[::2])

[19.62 22.9  15.44 42.02 43.71 23.51 43.33 15.07 31.56 38.04 37.94 19.06]


#
Partie 5 – Filtrage booléen Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les situations inhabituelles.  
1) Afficher les températures supérieures à 30 °C
2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C
3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. Déterminer anomalies, un tableau de booléen précisant les anomalies
4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies  

In [26]:
#Afficher les températures supérieures à 30 °C
print(temperatures_jour[temperatures_jour>30])

[37.2  31.01 42.56 42.02 43.71 33.18 43.33 40.58 30.64 31.56 38.04 37.94]


In [27]:
#Afficher les températures supérieures à 30 °C
print(temperatures_jour[(temperatures_jour<30)&(temperatures_jour>20)])

[22.9  23.51 29.56]


In [28]:
temperatures_jour

array([19.62, 37.2 , 22.9 , 31.01, 15.44, 42.56, 42.02, 16.  , 43.71,
       19.12, 23.51, 33.18, 43.33, 40.58, 15.07, 30.64, 31.56, 29.56,
       38.04, 19.82, 37.94, 15.62, 19.06, 18.49])

In [29]:
#Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. Déterminer anomalies, un tableau de booléen précisant les anomalies
anomalies=temperatures_jour>35
anomalies

array([False,  True, False, False, False,  True,  True, False,  True,
       False, False, False,  True,  True, False, False, False, False,
        True, False,  True, False, False, False])

In [30]:
#la somme des anomalies
som=np.sum(anomalies)
print(som)

8


#
Partie 6 – Manipulation des dimensions On suppose qu’on a 5 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée
2) Transformer la matrice en un tableau unidimensionnel
3) Déterminer la transposée de la matrice
4) Extraire toutes les mesures du capteur 1 ;
5) Extraire toutes les mesures du capteur 5 ;
 6) Extraire les mesures de tous les capteurs à 10h ;
 7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.

In [76]:
#Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée
matrice = np.random.uniform(15, 45, (5, 24)).round(2)
print(matrice)


[[24.33 27.35 21.76 23.12 18.22 39.33 22.38 34.02 25.81 15.15 22.42 39.9
  27.33 17.7  44.24 34.57 34.68 42.83 42.99 41.35 27.05 23.37 29.43 37.7 ]
 [30.27 26.26 32.93 34.26 44.36 33.65 26.8  43.05 36.95 27.92 28.79 44.96
  43.91 15.2  40.38 25.87 26.92 23.83 33.44 20.3  21.25 21.49 31.84 18.09]
 [24.34 39.21 29.58 43.67 36.44 18.46 28.44 30.8  41.89 42.61 16.6  42.29
  35.67 32.23 42.55 27.15 35.17 39.76 39.48 31.81 31.79 40.74 21.17 36.47]
 [39.48 18.58 40.46 18.76 16.61 29.12 43.16 43.43 32.6  39.39 22.54 34.23
  19.97 22.6  42.94 41.92 37.29 29.21 41.42 20.12 30.24 32.98 16.12 39.47]
 [23.45 42.76 42.99 38.63 39.81 24.09 19.76 25.99 26.8  43.08 39.9  40.21
  35.8  38.94 28.94 42.   44.11 27.34 42.17 36.38 34.26 30.77 43.33 25.88]]


In [77]:
#Transformer la matrice en un tableau unidimensionnel avec flatten
tableau_unidimensionnel = matrice.flatten()
print(tableau_unidimensionnel)

[24.33 27.35 21.76 23.12 18.22 39.33 22.38 34.02 25.81 15.15 22.42 39.9
 27.33 17.7  44.24 34.57 34.68 42.83 42.99 41.35 27.05 23.37 29.43 37.7
 30.27 26.26 32.93 34.26 44.36 33.65 26.8  43.05 36.95 27.92 28.79 44.96
 43.91 15.2  40.38 25.87 26.92 23.83 33.44 20.3  21.25 21.49 31.84 18.09
 24.34 39.21 29.58 43.67 36.44 18.46 28.44 30.8  41.89 42.61 16.6  42.29
 35.67 32.23 42.55 27.15 35.17 39.76 39.48 31.81 31.79 40.74 21.17 36.47
 39.48 18.58 40.46 18.76 16.61 29.12 43.16 43.43 32.6  39.39 22.54 34.23
 19.97 22.6  42.94 41.92 37.29 29.21 41.42 20.12 30.24 32.98 16.12 39.47
 23.45 42.76 42.99 38.63 39.81 24.09 19.76 25.99 26.8  43.08 39.9  40.21
 35.8  38.94 28.94 42.   44.11 27.34 42.17 36.38 34.26 30.77 43.33 25.88]


In [78]:
#Déterminer la transposée de la matrice les ligne devienne des collonnes et vice vers ca
transposée = matrice.T
print(transposée)

[[24.33 30.27 24.34 39.48 23.45]
 [27.35 26.26 39.21 18.58 42.76]
 [21.76 32.93 29.58 40.46 42.99]
 [23.12 34.26 43.67 18.76 38.63]
 [18.22 44.36 36.44 16.61 39.81]
 [39.33 33.65 18.46 29.12 24.09]
 [22.38 26.8  28.44 43.16 19.76]
 [34.02 43.05 30.8  43.43 25.99]
 [25.81 36.95 41.89 32.6  26.8 ]
 [15.15 27.92 42.61 39.39 43.08]
 [22.42 28.79 16.6  22.54 39.9 ]
 [39.9  44.96 42.29 34.23 40.21]
 [27.33 43.91 35.67 19.97 35.8 ]
 [17.7  15.2  32.23 22.6  38.94]
 [44.24 40.38 42.55 42.94 28.94]
 [34.57 25.87 27.15 41.92 42.  ]
 [34.68 26.92 35.17 37.29 44.11]
 [42.83 23.83 39.76 29.21 27.34]
 [42.99 33.44 39.48 41.42 42.17]
 [41.35 20.3  31.81 20.12 36.38]
 [27.05 21.25 31.79 30.24 34.26]
 [23.37 21.49 40.74 32.98 30.77]
 [29.43 31.84 21.17 16.12 43.33]
 [37.7  18.09 36.47 39.47 25.88]]


In [79]:
#Extraire toutes les mesures du capteur 1 ; matrice[lignes, colonnes]
matrice[0,:]

array([24.33, 27.35, 21.76, 23.12, 18.22, 39.33, 22.38, 34.02, 25.81,
       15.15, 22.42, 39.9 , 27.33, 17.7 , 44.24, 34.57, 34.68, 42.83,
       42.99, 41.35, 27.05, 23.37, 29.43, 37.7 ])

In [80]:
matrice[0]

array([24.33, 27.35, 21.76, 23.12, 18.22, 39.33, 22.38, 34.02, 25.81,
       15.15, 22.42, 39.9 , 27.33, 17.7 , 44.24, 34.57, 34.68, 42.83,
       42.99, 41.35, 27.05, 23.37, 29.43, 37.7 ])

In [81]:
#Extraire toutes les mesures du capteur 5 ;
matrice[4:1]


array([], shape=(0, 24), dtype=float64)

In [84]:
#Extraire les mesures de tous les capteurs à 10h ;
matrice[:,10]

array([22.42, 28.79, 16.6 , 22.54, 39.9 ])

In [85]:
#Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.
matrice[2:5,8:13]

array([[41.89, 42.61, 16.6 , 42.29, 35.67],
       [32.6 , 39.39, 22.54, 34.23, 19.97],
       [26.8 , 43.08, 39.9 , 40.21, 35.8 ]])

#
Partie 7 – Concaténation On suppose qu’on a un 2nd bâtiment avec 3 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs durant une journée

2) Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par les 8 capteurs durant une journée

In [75]:
# Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs durant une journée
matrice_2 = np.random.uniform(15, 45, (3, 24)).round(2)
print(matrice_2)

[[16.14 19.65 20.12 38.11 22.18 37.42 25.42 34.84 34.64 21.99 27.63 35.3
  33.16 33.26 16.18 42.16 41.67 20.36 26.64 42.23 28.56 28.   36.29 19.83]
 [40.91 15.42 17.22 26.28 22.48 30.38 19.3  34.25 31.17 39.9  23.07 20.13
  30.79 22.26 28.69 18.49 32.99 40.1  42.37 43.52 32.45 30.44 38.3  35.16]
 [19.91 27.83 19.63 32.   30.27 28.61 44.73 42.   19.54 33.23 29.35 39.86
  42.88 39.86 15.8  41.71 19.93 25.02 26.32 39.55 20.94 20.28 44.77 16.34]]


In [86]:
#Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par les 8 capteurs durant une journée
fusion_capteur=np.concatenate((matrice,matrice_2),axis=0)
print(fusion_capteur)

[[24.33 27.35 21.76 23.12 18.22 39.33 22.38 34.02 25.81 15.15 22.42 39.9
  27.33 17.7  44.24 34.57 34.68 42.83 42.99 41.35 27.05 23.37 29.43 37.7 ]
 [30.27 26.26 32.93 34.26 44.36 33.65 26.8  43.05 36.95 27.92 28.79 44.96
  43.91 15.2  40.38 25.87 26.92 23.83 33.44 20.3  21.25 21.49 31.84 18.09]
 [24.34 39.21 29.58 43.67 36.44 18.46 28.44 30.8  41.89 42.61 16.6  42.29
  35.67 32.23 42.55 27.15 35.17 39.76 39.48 31.81 31.79 40.74 21.17 36.47]
 [39.48 18.58 40.46 18.76 16.61 29.12 43.16 43.43 32.6  39.39 22.54 34.23
  19.97 22.6  42.94 41.92 37.29 29.21 41.42 20.12 30.24 32.98 16.12 39.47]
 [23.45 42.76 42.99 38.63 39.81 24.09 19.76 25.99 26.8  43.08 39.9  40.21
  35.8  38.94 28.94 42.   44.11 27.34 42.17 36.38 34.26 30.77 43.33 25.88]
 [16.14 19.65 20.12 38.11 22.18 37.42 25.42 34.84 34.64 21.99 27.63 35.3
  33.16 33.26 16.18 42.16 41.67 20.36 26.64 42.23 28.56 28.   36.29 19.83]
 [40.91 15.42 17.22 26.28 22.48 30.38 19.3  34.25 31.17 39.9  23.07 20.13
  30.79 22.26 28.69 18.49 32.99 40

In [87]:
#autre methode
fusion_capteur=np.vstack((matrice,matrice_2))
print(fusion_capteur)

[[24.33 27.35 21.76 23.12 18.22 39.33 22.38 34.02 25.81 15.15 22.42 39.9
  27.33 17.7  44.24 34.57 34.68 42.83 42.99 41.35 27.05 23.37 29.43 37.7 ]
 [30.27 26.26 32.93 34.26 44.36 33.65 26.8  43.05 36.95 27.92 28.79 44.96
  43.91 15.2  40.38 25.87 26.92 23.83 33.44 20.3  21.25 21.49 31.84 18.09]
 [24.34 39.21 29.58 43.67 36.44 18.46 28.44 30.8  41.89 42.61 16.6  42.29
  35.67 32.23 42.55 27.15 35.17 39.76 39.48 31.81 31.79 40.74 21.17 36.47]
 [39.48 18.58 40.46 18.76 16.61 29.12 43.16 43.43 32.6  39.39 22.54 34.23
  19.97 22.6  42.94 41.92 37.29 29.21 41.42 20.12 30.24 32.98 16.12 39.47]
 [23.45 42.76 42.99 38.63 39.81 24.09 19.76 25.99 26.8  43.08 39.9  40.21
  35.8  38.94 28.94 42.   44.11 27.34 42.17 36.38 34.26 30.77 43.33 25.88]
 [16.14 19.65 20.12 38.11 22.18 37.42 25.42 34.84 34.64 21.99 27.63 35.3
  33.16 33.26 16.18 42.16 41.67 20.36 26.64 42.23 28.56 28.   36.29 19.83]
 [40.91 15.42 17.22 26.28 22.48 30.38 19.3  34.25 31.17 39.9  23.07 20.13
  30.79 22.26 28.69 18.49 32.99 40